# -*- coding: utf-8 -*-
"""Chapter data for the four combined section videos.
Times are seconds into the combined video, read off the Fireflies transcripts.
To add or fix a chapter: edit the list, then run build_site.py."""

def t(x):
    p=[int(v) for v in x.split(":")]
    return p[0]*60+p[1] if len(p)==2 else p[0]*3600+p[1]*60+p[2]

MASTERCLASS=[
 ("0:00","The 4 Sub-Conscious Client Acquisition Hacks"),
 ("0:15","Hawkins' map of consciousness"),
 ("1:15","Hack 1 — operate in positive states"),
 ("2:09","DMs sent from desire and fear"),
 ("4:10","A DM sent from pride"),
 ("4:27","The Joe conversation, worked line by line"),
 ("6:04","Hack 2 — frame control"),
 ("6:44","Using humour to keep it light"),
 ("7:31","Staying non-reactive"),
 ("9:12","Hack 3 — emotional antifragility"),
 ("10:19","Lead abundance as the precondition"),
 ("11:14","Hack 4 — detach from the sale"),
 ("11:38","Reframing intrusive thoughts"),
 ("13:50","More reframes, worked through"),
 ("16:04","Taking note without self-sabotage"),
 ("17:07","LinkedIn DM Masterclass — Sales Navigator targeting"),
 ("18:41","Connection volume and acceptance rate"),
 ("19:05","The initial DM framework, line by line"),
 ("19:46","Restrained compliments and authority lines"),
 ("20:24","Ending on a commonality"),
 ("20:37","The three levels of prospect interest"),
 ("21:23","Touchpoints before you DM"),
 ("23:56","Troubleshooting a low acceptance rate"),
 ("25:29","Sales assets — leading with value"),
 ("27:31","Handling objections in the DMs"),
 ("30:10","The results database"),
 ("32:00","Matching a case study to the prospect"),
 ("34:37","A cold prospect worked end to end"),
 ("36:12","Why the last message is the preview"),
 ("36:52","Reverse Engineering How to Convey Yourself"),
 ("37:02","The friendly helper mindset"),
 ("37:56","Rereading your DMs the next day"),
 ("39:00","Multi-thread conversations"),
 ("39:24","How the prospect wants to see you"),
 ("40:04","Building an AI sales coach"),
 ("41:00","The pre-call and post-call drips"),
 ("46:35","Mirroring their energy"),
 ("49:30","Training the bot on your own material"),
 ("51:06","The state you DM from"),
 ("53:56","Relevance, competence and genuine care"),
 ("55:43","Non-neediness and enforcing boundaries"),
 ("59:01","Speed to lead"),
 ("1:00:31","Reply & Objection Handling"),
 ("1:01:00","Every reply is salvageable"),
 ("1:02:30","Getting back to the call without pressure"),
 ("1:04:01","Priming a specific pain point"),
 ("1:06:00","Giving the power back"),
 ("1:07:30","Long messages, and when they work"),
 ("1:09:02","Name-dropping to build relevance"),
 ("1:12:02","When they say they'll book and don't"),
 ("1:15:00","Reminding without sounding needy"),
 ("1:16:30","Handling “my time is scarce”"),
 ("1:18:04","Q&A on follow-up messages"),
 ("1:19:32","Why “why aren't you interested” fails"),
 ("1:24:00","Follow Up DMs"),
 ("1:25:32","Why follow-ups are more formulaic than replies"),
 ("1:27:00","Gauging their interest level"),
 ("1:28:31","Follow-up examples"),
 ("1:30:00","Voice messages as follow-ups"),
 ("1:33:04","Following up with people who said they'd book"),
 ("1:34:30","The three ways humans communicate"),
 ("1:36:00","Soliciting an introduction"),
 ("1:37:30","Interest levels are always moving"),
 ("1:39:00","Following up on old clients"),
 ("1:42:04","Follow-up timing"),
 ("1:43:34","The non-needy nudge"),
 ("1:46:32","Cutting the question mark"),
 ("1:48:00","Don't resend the link"),
 ("1:51:03","Showing them the value of the conversation"),
 ("1:52:30","One word changes the whole message"),
 ("1:54:01","Q&A: connection limits"),
 ("1:55:22","LinkedIn Content"),
 ("1:56:43","Reposting and building engagement"),
 ("1:57:21","The AI content bot"),
 ("1:59:20","Scaling comments"),
 ("2:00:40","Formatting posts to be skimmable"),
 ("2:02:02","Memes"),
 ("2:02:42","Collaboration posts"),
 ("2:06:01","Reviewing a post together"),
 ("2:07:22","Writing a better hook"),
 ("2:09:23","Post structure"),
 ("2:10:35","Sales Systems"),
 ("2:11:21","Qualifying from the questionnaire"),
 ("2:12:00","Framing the investment question"),
 ("2:13:30","Setting your availability"),
 ("2:15:00","The pre-call email drip"),
 ("2:16:32","Sending social proof"),
 ("2:18:00","The case study as a lead magnet"),
 ("2:19:33","Why the delays are set that way"),
 ("2:21:01","Texting prospects the morning of the call"),
 ("2:22:32","Why text beats email when they cancel"),
 ("2:24:04","Setting up the follow-up call"),
 ("2:25:30","The CRM columns"),
 ("2:27:05","Recycling social proof"),
 ("2:28:38","The $4,000 deal breakdown"),
 ("2:30:00","Moving prospects from hot to follow-up"),
 ("2:31:30","Staying top of mind without pushing"),
 ("2:33:03","Wrap-up"),
]

TRAINING=[
 ("0:00","How to Properly Use LinkedIn Sales Navigator"),
 ("1:16","Boolean exclusions on keywords"),
 ("5:01","Saving the search"),
 ("6:41","How to Set Up Dripify"),
 ("8:00","Daily limits and working hours"),
 ("10:05","Creating a campaign and adding leads"),
 ("12:31","Building the campaign sequence"),
 ("18:46","Acceptance and reply rates"),
 ("20:53","LinkedIn Profile Mini Masterclass"),
 ("22:31","Photo, banner and headline"),
 ("23:48","The About section"),
 ("25:07","Featured and experience"),
 ("27:30","Skills and recommendations"),
 ("29:53","A second profile worked through"),
 ("33:39","The 5 Levels of Prospect Warmth"),
 ("35:05","Level 1 — neutral"),
 ("36:16","Level 2 — profile viewers"),
 ("37:30","Level 3 — content engagers"),
 ("38:45","Level 4 — lead magnet engagers"),
 ("40:00","Level 5 — inbound leads"),
 ("41:38","Recap of the five levels"),
 ("44:38","Voice Message Mini Masterclass"),
 ("46:19","When to send a voice message"),
 ("47:30","Outcome independence in your tone"),
 ("50:01","Foreshadowing value out loud"),
 ("53:45","Using your WDYM phrase"),
 ("55:01","How to position the call"),
]

MACRO=[
 ("0:00","Conveying Spontaneity"),
 ("2:23","Differentiating Line Lengths"),
 ("3:58","Frame Control"),
 ("6:46","Building an authoritative frame"),
 ("8:20","Foreshadowing an introduction"),
 ("10:08","Authority-building observations"),
 ("12:26","The Cheat Code to Sign More Clients"),
 ("15:07","Sending value after they book"),
 ("17:24","Multi-Thread Conversations"),
 ("21:31","No Shame In Your Game"),
 ("24:58","Non-Needy Call Pitches"),
 ("26:34","Open Up"),
 ("28:21","Telling specific stories"),
 ("30:42","Play Devil's Advocate"),
 ("32:13","Reflecting, Resonating & Mirroring"),
 ("35:01","Mirroring what they say"),
 ("36:40","A conversation worked through"),
 ("40:46","Speak Your DMs Out Loud"),
 ("42:29","Specificity"),
 ("45:00","Specific advice beats general advice"),
 ("49:02","SURE Language"),
 ("49:53","The Friendly Helper Mindset"),
 ("53:27","Throwing rope"),
 ("56:41","Doing things differently"),
 ("58:22","A conversation worked through"),
 ("1:03:27","Help at all costs"),
 ("1:04:41","The Restrained Compliment"),
 ("1:06:40","Frameworks, not scripts"),
 ("1:07:49","LinkedIn's Never Ending Rabbit Hole"),
]

MICRO=[
 ("0:00","Be Unsure of Time Availability"),
 ("2:37","Contractions"),
 ("4:44","Don't DM Green Rings"),
 ("5:42","Don't Edit or Delete DMs"),
 ("6:34","Foreshadow Intro Before Business Questions"),
 ("8:32","Foreshadow Intro With Ty"),
 ("10:15","Foreshadow Visiting Each Other"),
 ("12:06","Haha vs. Hahaha"),
 ("14:44","Handling 10 out of 10 Interest With No Clarity"),
 ("17:18","If I Can Help"),
 ("19:50","Mention Relevant Big Names"),
 ("22:24","Mention Where You're At Now"),
 ("23:30","Please Keep This Between Us"),
 ("25:11","Rephrase Their Offer"),
 ("27:34","Texting Prospects Day of Sales Call"),
 ("29:19","The Breakup Message"),
 ("30:56","The Conscious Typo"),
 ("32:11","The Question Attack"),
 ("37:32","Wait So"),
 ("40:03","WDYM Phrases"),
]


ANSWERS=[
 ("0:00","How to DM the 6 Levels of Prospect Warmth"),
 ("1:27","Level 1 — neutral prospects"),
 ("2:48","The initial DM, worked line by line"),
 ("4:12","Answering “what's in it for me”"),
 ("5:28","Why your friends' success rubs off on you"),
 ("6:13","Level 2 — profile viewers"),
 ("8:17","How fast to reach out"),
 ("9:32","What changes once they've seen your profile"),
 ("11:37","Getting the greeting right"),
 ("12:51","Level 3 — connection requests"),
 ("14:52","DMing someone who requested you"),
 ("16:47","Calibrating your enthusiasm"),
 ("17:34","A connection-request DM worked through"),
 ("18:50","Level 4 — content engagers"),
 ("20:50","Knowing what a qualified prospect looks like"),
 ("21:29","Using the post they engaged with"),
 ("23:18","Level 5 — lead magnet engagers"),
 ("24:30","The lead magnet DM"),
 ("25:31","Send the resource, then the question"),
 ("27:22","Level 6 — inbound leads"),
 ("28:04","Sending value after they book"),
 ("28:43","Q&A: are clients friends?"),
 ("30:01","The outreach asset library"),
 ("31:55","Opening small and going wide"),
 ("33:18","The first question to ask"),
 ("34:37","Live Answers — brand strategy first"),
 ("36:24","Getting prospects to indicate interest"),
 ("37:03","Building relationships with adjacent creators"),
 ("38:53","Why the brand has to come first"),
 ("40:12","Ten ways to solicit interest"),
 ("41:19","Getting people to view your profile"),
 ("42:22","Talking about the result you sell"),
 ("43:51","Q&A: running a second profile"),
 ("44:27","Why splitting focus costs you"),
 ("45:52","Following up once they've shown interest"),
 ("47:03","Conveying genuine care"),
 ("47:45","Adding value in a follow-up"),
 ("49:05","Foreshadowing an introduction"),
 ("50:36","Throwing rope"),
 ("51:09","Asking the same question again, properly"),
 ("53:09","Why the small detail matters"),
 ("54:37","When they're already working with someone"),
 ("55:23","Relieving the tension"),
 ("57:47","Follow-up cadence by interest level"),
 ("58:56","When to stop following up"),
 ("1:00:13","Reconnecting weeks later"),
 ("1:01:27","Integrity through the sales process"),
 ("1:02:43","Live Answers — introductions"),
 ("1:05:50","How the Q&A runs"),
 ("1:06:33","LinkedIn action limits"),
 ("1:07:17","Mid-market and enterprise DMs"),
 ("1:07:57","The 30 DM conversations resource"),
 ("1:08:39","Priming pain points"),
 ("1:09:58","Your most ambiguous question first"),
 ("1:11:21","Mentioning your offer early"),
 ("1:12:43","Keeping the conversation real"),
 ("1:14:16","Cold outbound versus building the brand"),
 ("1:16:01","Timing, and the size of your pool"),
 ("1:18:45","Profile views as a signal"),
 ("1:19:22","Commenting to build relationships"),
 ("1:20:37","Reaching out to bigger creators"),
 ("1:21:52","Do perfect prospects get special treatment?"),
 ("1:22:34","Free work versus lead magnets"),
 ("1:24:31","Why free work stopped working"),
 ("1:25:51","Not putting prospects on a pedestal"),
 ("1:26:30","Being aware of your own eagerness"),
 ("1:28:36","Reaching several people at one company"),
 ("1:29:19","Processing negative states"),
 ("1:30:50","Being before doing"),
 ("1:32:13","Meditation and the business"),
 ("1:33:28","Getting the profile right first"),
 ("1:34:37","The daily DM plan"),
 ("1:35:18","Live Answers — DM feedback session"),
 ("1:36:03","A year of these calls"),
 ("1:37:17","Reviewing an offer campaign"),
 ("1:38:35","Taking control of the screen"),
 ("1:39:15","Authority observations that land"),
 ("1:39:54","Answering “what's in it for me” every time"),
 ("1:41:10","Using social proof without sounding salesy"),
 ("1:43:19","How many follow-ups before you stop"),
 ("1:43:53","Reverse pitches"),
 ("1:45:07","Handling a reverse pitch politely"),
 ("1:46:21","Spotting active prospects"),
 ("1:47:37","Sticking to one niche"),
 ("1:48:43","Structuring the lead magnet"),
 ("1:49:56","What a good lead magnet looks like"),
 ("1:51:39","Better DM questions"),
 ("1:52:56","Injecting humour"),
 ("1:53:38","Foreshadowing intros and referral partnerships"),
 ("1:55:32","Pitching the call sooner"),
 ("1:56:46","Getting confident enough to pitch early"),
 ("1:58:05","Unqualified prospects"),
 ("1:59:18","Reviewing Disha's DMs"),
 ("2:00:36","Rephrasing their offer"),
 ("2:02:01","Getting specific"),
 ("2:02:42","Building authority in the DM"),
 ("2:03:18","Where the frame gets lost"),
 ("2:05:04","Live Answers — bigger deal sizes"),
 ("2:06:25","Delegating sales tasks"),
 ("2:07:35","What your hour is worth"),
 ("2:08:55","LinkedIn commenting"),
 ("2:09:37","Voice notes and accents"),
 ("2:11:41","Improving your English"),
 ("2:13:36","Choosing your niche"),
 ("2:14:19","Which niches are worth it"),
 ("2:15:45","Picking one target market"),
 ("2:17:11","Multiple ICPs and ROI"),
 ("2:19:50","When the niches are all different"),
 ("2:21:19","Results and lead magnets"),
 ("2:23:11","Using the Lab AI"),
 ("2:24:20","Daily DM volume"),
 ("2:26:14","Building DM consistency"),
 ("2:27:34","Lead magnet frequency"),
 ("2:28:09","Content posting frequency"),
 ("2:28:53","Selling without results"),
 ("2:30:20","Using client social proof"),
 ("2:31:28","Keeping it above board"),
]

# Standalone hubs that live in the portal but keep their own layout.
# They open in a new tab; nothing is injected into them, so each file stays
# shareable on its own.
EXTRAS=[
 dict(slug="sales-navigator-hub", name="Sales Navigator", nav="Sales Navigator",
      path="tools/sales-navigator-hub.html", g=("#D8434B","#EF6A52"),
      icon='<path d="m21 21-4.35-4.35"/><circle cx="11" cy="11" r="7"/><path d="M11 8v6M8 11h6"/>'),
]

SECTIONS=[
 dict(slug="1-masterclass", name="Masterclass", nav="Masterclass",
      vid="hEbu8Gaedtc", dur="2:34:04", g=("#4B3FD1","#7C3FD1"), ch=MASTERCLASS,
      old_prefix="1-"),
 dict(slug="2-training", name="Training", nav="Training",
      vid="GTgbPBhUoy0", dur="58:38", g=("#0E7F8C","#12A37C"), ch=TRAINING,
      old_prefix="2-"),
 dict(slug="3-macro-dm", name="Macro DM", nav="Macro DM",
      vid="X7dk3BbIgpE", dur="1:10:44", g=("#2544C4","#1E8AD6"), ch=MACRO,
      old_prefix="3-"),
 dict(slug="4-micro-dm", name="Micro DM", nav="Micro DM",
      vid="EHGXGwKcU6k", dur="42:23", g=("#A82C9E","#D43C77"), ch=MICRO,
      old_prefix="4-"),
 dict(slug="5-answers", name="Answers", nav="Answers",
      vid="9c9i9MgO4Ug", dur="2:32:10", g=("#C07A16","#D65E28"), ch=ANSWERS,
      old_prefix="5-"),
]
for s in SECTIONS:
    s["chapters"]=[[t(a),b] for a,b in s["ch"]]
